### ISSUE TITLE
Error I can't run it 

### ISSUE THREAD

**Issue by 4kek** [9P9/Discord-QR-Token-Logger#37] opened 2022-10-07 17:45 UTC
File "C:\Users\***********\Desktop\Discord-QR-Token-Logger-main\main.py", line 24, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by mouadessalim** [comment] 2022-10-07 17:58
please try: `pip install beautifulsoup4`

**Comment by 4kek** [comment] 2022-10-07 18:20
Requirement already satisfied: beautifulsoup4 in c:\users\***********\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\**********\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from beautifulsoup4) (2.3.2.post1)

**Comment by mouadessalim** [comment] 2022-10-07 18:28
If you installed the modules and it didn't work that mean the problem is coming from your environment. It is not coming from the script. The fact that you may have several Python version installed. Try to check if it's the case.

**Comment by 4kek** [comment] 2022-10-07 18:52
I deleted python and reinstalled it nothing changed

**Comment by mrdogesgunship** [comment] 2022-10-08 07:47
i have the same issue

**Comment by mouadessalim** [comment] 2022-10-10 11:38
The current issue does not come from the project itself but from your environment. **Therefore, I am afraid to close this issue for the reason that i can't help you because I don't have access to your machines.**
 
So try to see on your side why you can't install the module or use it. The most common reasons come due to the installation of modules from `PIP` or from the installation folder, this kind of error can also come from incompatibility due to having several version of Python installed in your machines. Try to find an answer to your problem in the web. I highly recommand to  search on **_StackOverFlow_**.

Good luck @mrdogesgunship @4kek ❤️.

Don't forget to star the project 👋 !

**Closed by mouadessalim** 2022-10-10 11:38 UTC
Labels: needs-repo
